### ISSUE TITLE
BLE in Action

### ISSUE THREAD

**Issue by phodal** [phodal/ideas#38]

**Comment by lucyking** [comment]
BLE不能和正常蓝牙通信的（如果你的说的是蓝牙

**Comment by phodal** [comment]
@lucyking 我说的是BLE哦~~

**Comment by lucyking** [comment]
@phodal 之前搞过CC2540 还有cc-debuger 你需要硬件吗

**Comment by phodal** [comment]
@lucyking 暂时不需要。。因为我在搬家，不知道还要丢多少东西。。

**Comment by lucyking** [comment]
there :articulated_lorry:
