### ISSUE TITLE
基于Git/GitHub的手机电子书编写软件

### ISSUE THREAD

**Issue by phodal** [phodal/ideas#52]

**Comment by snowdream** [comment]
gitbook是一个使用node编写的电子书方案，通过gitbook，用户可以使用markdown等编写电子书，然后生成html，pdf，epub，mobi等各式。

基于简单的方式，我把gitbook生成的html，封装在Android app中，做成一个离线电子书。https://github.com/snowdream/gitbook-android   
我觉得可以参考这个方案。

**Comment by phodal** [comment]
@snowdream 我打算拿Hybird写一个

**Comment by phodal** [comment]
https://github.com/phodal/mole
