### ISSUE TITLE
基于GitHub的云笔记

### ISSUE THREAD

**Issue by phodal** [phodal/ideas#59]
- [ ] #50 基于Git/GitHub的在线电子书协作平台
- [ ] #52 基于Git/GitHub的手机电子书编写软件

**Comment by phodal** [comment]
https://github.com/buunguyen/octotree
https://github.com/Automattic/wp-calypso

**Comment by phodal** [comment]
https://github.com/Automattic?utf8=%E2%9C%93&query=simplenote

**Comment by phodal** [comment]
https://github.com/chentsulin/electron-react-boilerplate
https://github.com/unimonkiez/react-cordova-boilerplate
https://github.com/kriasoft/react-starter-kit

**Comment by vmlinz** [comment]
参考https://github.com/prose/prose

我已经在使用他们来做cms了，配合ci和github pages，可以实现一个编辑和排版分离的内容管理系统。

**Comment by phodal** [comment]
https://github.com/phodal/mole
